### ISSUE TITLE
Errors in Blender 3.5

### ISSUE THREAD

**Issue by hectorC** [jlampel/voronoi_scatter#26]
Attempting to create a Scatter Images node group throws the following errors (username replaced with "*"):
`
Python: Traceback (most recent call last):
  File "C:\Users\*\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\voronoi_scatter\voronoi_scattering.py", line 1044, in execute
    voronoi_scatter(self, context, get_scatter_sources(context.selected_nodes))
  File "C:\Users\*\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\voronoi_scatter\voronoi_scattering.py", line 878, in voronoi_scatter
    scatter_node = setup_scatter_node(self, context, selected_nodes)
  File "C:\Users\*\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\voronoi_scatter\voronoi_scattering.py", line 685, in setup_scatter_node
    blending_results = blend_colors(self, scatter_node, scatter_sources)
  File "C:\Users\*\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\voronoi_scatter\voronoi_scattering.py", line 251, in blend_colors
    blending_node = noise_blend(self, nodes_to_mix, color_results, 'custom')
  File "C:\Users\*\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\voronoi_scatter\noise_blending.py", line 221, in noise_blend
    blending_node = create_group()
  File "C:\Users\*\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\voronoi_scatter\noise_blending.py", line 106, in create_group
    blending_inputs["Vector"].hide_value = True
KeyError: 'bpy_prop_collection[key]: key "Vector" not found'
`

**Comment by jlampel** [comment]
Thank you for letting me know! I believe I know what the cause of this is. I'll get a new version out for 3.5 as soon as I can.

**Comment by hectorC** [comment]
Thank you. It seems to be related to Python API changes in 3.5, The noise blending node is failing to fully generate.

**Comment by jlampel** [comment]
Ok, I have this fixed and will release a new version shortly! Just need to tie up a few other loose ends as well.
