### ISSUE TITLE
Object in edit mode will trigger wrong context error

### ISSUE THREAD

**Issue by varkenvarken** [jlampel/voronoi_scatter#5]
If an object is in edit mode, applying the voronoi scatter operator to an image in the shader editor will fail with a context incorrect error (see below).  Version info: Scattershot 1.2, Blender 2.93.4 LTS

`location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/home/michel/.config/blender/2.93/scripts/addons/voronoi_scatter/voronoi_scattering.py", line 746, in execute
    voronoi_scatter(self, context)
  File "/home/michel/.config/blender/2.93/scripts/addons/voronoi_scatter/voronoi_scattering.py", line 642, in voronoi_scatter
    scatter_node = setup_scatter_node(self, selected_nodes)
  File "/home/michel/.config/blender/2.93/scripts/addons/voronoi_scatter/voronoi_scattering.py", line 454, in setup_scatter_node
    scatter_node = append_scatter_node(self, selected_nodes)
  File "/home/michel/.config/blender/2.93/scripts/addons/voronoi_scatter/voronoi_scattering.py", line 57, in append_scatter_node
    scatter_node = append_node(nodes, 'SS - Scatter Fast')
  File "/home/michel/.config/blender/2.93/scripts/addons/voronoi_scatter/utilities.py", line 10, in append_node
    bpy.ops.wm.append(filename=node_tree_name, directory=path)
  File "/home/michel/Downloads/blender-2.93.4-linux-x64/2.93/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.wm.append.poll() failed, context is incorrect`

**Comment by jlampel** [comment]
Thank you for letting me know and for finding a fix! Much appreciated. I'm in the middle of rewriting a good chunk of it, so I'll be sure to include this as well. Another solution may be to switch to object mode (if not already) and switch back afterwards so the user won't have to wonder why it's disabled.

**Comment by varkenvarken** [comment]
I would indeed consider switching to object mode even more user friendly
but I was in a hurry :-)

Looking forward to the update; keep up the good work!

-- Michel.
